server:
  port: 8082
spring:
  application:
    name:
      ms-gerenciamento-catalogo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cinema_catalogo
    username: root
    password: 121105
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
  spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            secret-key: ${JWT_SECRET:123456789}
springdoc:
  api-docs:
    path: /book-service/v3/api-docs
  swagger-ui:
    url: /book-service/v3/api-docs
  override-server-url: true