name: Cinema Microservices CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Build and Test ms-autenticacao-cinema with Maven
      working-directory: ./ms-autenticacao-cinema
      run: mvn clean package

    - name: Build and Test ms-gerenciamento-catalogo with Maven
      working-directory: ./ms-gerenciamento-catalogo
      run: mvn clean package

    - name: Build and Test ms-gerenciamento-clientes with Maven
      working-directory: ./ms-gerenciamento-clientes
      run: mvn clean package

    - name: Build and Test ms-gerenciamento-sessoes with Maven
      working-directory: ./ms-gerenciamento-sessoes
      run: mvn clean package

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build Docker Images
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ms-autenticacao-cinema:latest ./ms-autenticacao-cinema
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ms-gerenciamento-catalogo:latest ./ms-gerenciamento-catalogo
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ms-gerenciamento-clientes:latest ./ms-gerenciamento-clientes
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ms-gerenciamento-sessoes:latest ./ms-gerenciamento-sessoes

    - name: Tag Docker Images with Run ID
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/ms-autenticacao-cinema:latest ${{ secrets.DOCKER_USERNAME }}/ms-autenticacao-cinema:${{ github.run_id }}
        docker tag ${{ secrets.DOCKER_USERNAME }}/ms-gerenciamento-catalogo:latest ${{ secrets.DOCKER_USERNAME }}/ms-gerenciamento-catalogo:${{ github.run_id }}
        docker tag ${{ secrets.DOCKER_USERNAME }}/ms-gerenciamento-clientes:latest ${{ secrets.DOCKER_USERNAME }}/ms-gerenciamento-clientes:${{ github.run_id }}
        docker tag ${{ secrets.DOCKER_USERNAME }}/ms-gerenciamento-sessoes:latest ${{ secrets.DOCKER_USERNAME }}/ms-gerenciamento-sessoes:${{ github.run_id }}

    - name: Push Docker Images to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/ms-autenticacao-cinema:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/ms-autenticacao-cinema:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/ms-gerenciamento-catalogo:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/ms-gerenciamento-catalogo:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/ms-gerenciamento-clientes:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/ms-gerenciamento-clientes:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/ms-gerenciamento-sessoes:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/ms-gerenciamento-sessoes:${{ github.run_id }}
      
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
